package com.fulltrix.tjfcore.api.pattern;

import com.fulltrix.tjfcore.api.TJFAPI;
import com.fulltrix.tjfcore.api.block.IFusionCoilBlockStats;
import gregtech.api.pattern.PatternStringError;
import gregtech.api.pattern.TraceabilityPredicate;
import gregtech.api.util.BlockInfo;
import net.minecraft.block.state.IBlockState;

import java.util.Comparator;
import java.util.LinkedList;
import java.util.function.Supplier;

public class TJFTraceabilityPredicate {
    public static Supplier<TraceabilityPredicate> FUSION_COILS = () -> new TraceabilityPredicate(blockWorldState -> {
        IBlockState blockState = blockWorldState.getBlockState();
        if (TJFAPI.FUSION_COILS.containsKey(blockState)) {
            IFusionCoilBlockStats stats = TJFAPI.FUSION_COILS.get(blockState);
            Object currentCoil = blockWorldState.getMatchContext().getOrPut("CoilType", stats);
            if (!currentCoil.equals(stats)) {
                blockWorldState.setError(new PatternStringError("gregtech.multiblock.pattern.error.coils"));
                return false;
            }
            blockWorldState.getMatchContext().getOrPut("VABlock", new LinkedList<>()).add(blockWorldState.getPos());
            return true;
        }
        return false;
    }, () -> TJFAPI.FUSION_COILS.entrySet().stream()
            // sort to make autogenerated jei previews not pick random coils each game load
            .sorted(Comparator.comparingInt(entry -> entry.getValue().getTier()))
            .map(entry -> new BlockInfo(entry.getKey(), null))
            .toArray(BlockInfo[]::new))
            .addTooltips("gregtech.multiblock.pattern.error.coils");

    public TJFTraceabilityPredicate() {
    }

}
